// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ageombpphwobyrknmumk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnZW9tYnBwaHdvYnlya25tdW1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MzEzNDMsImV4cCI6MjA3MTIwNzM0M30.QNclX3dHU6YX3wUomCU1xxPf-R0DVZnK6Qc9QaPQ980";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);